language: node_js
sudo: false
node_js:
  - "0.10"
git:
  depth: 10
install:
  - "git clone --depth=10 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
script:
  - "./bin/docdown ./node_modules/lodash/lodash.js output.md toc=\"categories\" url=\"https://github.com/lodash/lodash/blob/master/lodash.js\""
  - "cat output.md"
